
$computers = "KATHEHS-NA1","CENTRSCH-NA1","DRIPSHS-NA1","NTMSDRW-NA1","ALICESOA-NA1","KATHESOA-NA1","CENTRMS1-NA1","PALMEHS-NA1","MILINCEC-NA1","STUARSCH-NA1","YIRRKCEC-NA1","CASUAHS-NA1","TAMINHS-NA1","YUENDCEC-NA1","MANINCEC-NA1","RAMINCEC-NA1","DRIVESCH-NA1","DARWIMS-NA1","TENNAHS-NA1","ARLPAHS-NA1","BORROSCH-NA1","YIRRKHLC-NA1","NIGHTHS-NA1","NIGHTSCH-NA1","ALAWASCH-NA1","ALEKACEC-NA1","NHULUHS-NA1","HOWARSCH-NA1","WANGUSCH-NA1","JINGISCH-NA1","LEANYSCH-NA1","PIGEOSCH-NA1","GAPUWCEC-NA1","GIRRASCH-NA1","GRAYSCH-NA1","NGUKUCEC-NA1","DURACSCH-NA1","WUGULSCH-NA1","NGANMSCH-NA1","MACFASCH-NA1","MILLNSCH-NA1","SADADSCH-NA1","WULAGSCH-NA1","MANUNSCH-NA1","MOULDSCH-NA1","KALKACEC-NA1","ROBINSCH-NA1","LAJAMCEC-NA1","BAKEWSCH-NA1","ALYANAS-NA1","MINYESCH-NA1","CASUASCH-NA1","KARAMSCH-NA1","HUMPTSCH-NA1","AMPILSCH-NA1","JILKMSCH-NA1","LARAPSCH-NA1","GUNBACEC-NA1","BATCHAS-NA1","BERRYSCH-NA1","NEMARSCH-NA1","WARRUSCH-NA1","PARAPSCH-NA1","ANGURCEC-NA1","BRADSSCH-NA1","CLYDESCH-NA1","GILLESCH-NA1","JABIRAS-NA1","KATHESCH-NA1","LARRASCH-NA1","LUDMISCH-NA1","NAKARSCH-NA1","NUMBUSCH-NA1","SHEPHCEC-NA1","UMBAKSCH-NA1","WOODRSCH-NA1"


$computers | Foreach-Object { 
    if (Test-Connection $_ -Count 1 -Quiet ) {
        [PSCustomObject]@{
            Name = $_
            Ping = 'TRUE'
        } | export-csv pingout.csv -Append -NoTypeInformation
    } else {
        [PSCustomObject]@{
            Name = $_
            Ping = 'FALSE'
        } | export-csv pingout.csv -Append -NoTypeInformation
    }
}

